git:
  mainBranches:
    - master
    - main
    - trunk
  ignoreWhitespaceInDiffView: true
  pagers:
    - pager: ~/.config/theme-sync/bin/delta-auto

# quitOnTopLevelReturn: true
promptToReturnFromSubprocess: false
# os:
#   edit: "zed {{filename}}"
#   editAtLine: "zed {{filename}}:{{line}}"
