# Aliases
alias cat 'bat --style plain --pager never'
alias cp 'cp -i'
alias cpp 'cp -R'
alias df 'df -h'
alias du 'du -ch'
alias free 'free -m'
alias ga 'git add'
alias gc 'git commit'
alias gca 'git commit --amend'
alias gco 'git checkout'
alias gd 'git diff'
alias gdc 'git diff --cached'
alias gdpr 'gh pr create --draft'
alias gir 'git rebase -i'
alias gl 'git log --graph --pretty=format:'\''%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset'\'' --abbrev-commit'
alias gpr 'gh pr create'
alias gs 'git status'
alias k kubectl
alias l 'eza --group-directories-first -g -lbF --git --icons'
alias la 'eza --group-directories-first -g -lbhHigmuSa@ --time-style=long-iso --git --color-scale --icons'
alias ll 'eza --group-directories-first -g -lbF --git --icons -G'
alias ls 'eza --group-directories-first -g'
alias lsblk 'lsblk -o name,mountpoint,label,size,type,uuid'
alias lt 'eza --group-directories-first -g --tree --level=2 --icons'
alias tree 'eza -T'
alias mkdir 'mkdir -pv'
alias mux 'tmux a'
alias mv 'mv -i'
alias pull 'git pull'
alias push 'git push'
alias rmm 'rm -rvI'
alias tempty trash-empty
alias tl trash-list
alias tp trash-put
alias vimdiff 'nvim -d'
